version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: read_csv
        container_name: read_csv
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - shared-db:/var/www/html/database
            - shared-csv:/var/www/html/storage/app/csv
        environment:
            - "DB_CONNECTION=sqlite"
            - "DB_DATABASE=/var/www/html/database/database.sqlite"
        ports:
            - 8000:8000
        command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

    queue_worker:
        build: .
        command: sh -c "php artisan queue:work"
        environment:
            - "QUEUE_CONNECTION=database"
            - "DB_CONNECTION=sqlite"
            - "DB_DATABASE=/var/www/html/database/database.sqlite"
        volumes:
            - ./:/var/www/html
            - shared-db:/var/www/html/database
            - shared-csv:/var/www/html/storage/app/csv

volumes:
    shared-db:
    shared-csv:

